name: ps-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-script:
    runs-on: windows-latest   # istersen: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force


      - name: Run cleanup script (safe WhatIf)
        shell: pwsh
        run: pwsh ./scripts/Clean-TempFiles.ps1 -WhatIf

      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -Force -SkipPublisherCheck

            - name: Run Pester tests
        shell: pwsh
        run: |
          Import-Module Pester -Force
          Invoke-Pester -Path ./tests -Verbose -EnableExit
