name: ps-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-script:
    runs-on: windows-latest   # istersen: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Static analysis (fail only on Errors)
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path ./scripts -Recurse -Severity Error
          $results | Format-Table -AutoSize
          if ($results.Count -gt 0) { Write-Error "ScriptAnalyzer found errors."; exit 1 }

      - name: Run cleanup script (safe WhatIf)
        shell: pwsh
        run: pwsh ./scripts/Clean-TempFiles.ps1 -WhatIf

      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -Force -SkipPublisherCheck

      - name: Run Pester tests
        shell: pwsh
        run: |
          Import-Module Pester -Force
          $result = Invoke-Pester -Path ./tests -PassThru -Verbose
          if ($result.FailedCount -gt 0) { exit 1 }
